name: luvi_services
description: Local services package for LUVI app shared logic.
publish_to: 'none'

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.24.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.3

dev_dependencies:
  build_runner: ^2.10.1
  riverpod_generator: ^3.0.3
